### PR TITLE
Update llvm commit

### PR DESCRIPTION
**Pull request by yifeizh2**
Update llvm commit to involve the fix for unpack op canonicalization and `isaConvolutionOpInterface`.

PR #101 requires this update to pass CI check.

### CODE REVIEW

**Comment by Yun-Fly** [comment]
Do we need to update llvm version of IMEX as well?

**Comment by yifeizh2** [comment]
> Do we need to update llvm version of IMEX as well?

Yes. Thanks for remindering.

**Comment by Yun-Fly** [comment]
> > Do we need to update llvm version of IMEX as well?
> 
> Yes. Thanks for remindering.

If so, please also raise a PR in this [forked IMEX repo](https://github.com/Menooker/mlir-extensions) and request review of @dchigarev.

**Comment by yifeizh2** [comment]
@dchigarev Hi. The current updated llvm commit has caused page fault runtime error in gpu `mlp.mlir`. The current error message is as follows
```
FATAL: Unexpected page fault from GPU at 0x7efc5a1f7000, ctx_id: 1 (CCS) type: 0 (NotPresent), level: 1 (PDE), access: 0 (Read), banned: 1, aborting.
^
<stdin>:1:8: note: possible intended match here
FATAL: Unexpected page fault from GPU at 0x7efc5a1f7000, ctx_id: 1 (CCS) type: 0 (NotPresent), level: 1 (PDE), access: 0 (Read), banned: 1, aborting.
       ^
```
The detailed CI log is accessible at: https://github.com/intel/graph-compiler/actions/runs/11043869278/job/30678842932?pr=357.
Can you help troubleshoot this issue? Sorry for causing inconvenience.

**Comment by dchigarev** [comment]
> Hi. The current updated llvm commit has caused page fault runtime error in gpu mlp.mlir. The current error message is as follows

The `is-usm-args=false` parameter for gpu pipeline was missing for some reason in `mlp.mlir` test. Fixed this in f56eb398fcd08133788067649812619be1f79438 commit to this branch

**Comment by yifeizh2** [comment]
> > Hi. The current updated llvm commit has caused page fault runtime error in gpu mlp.mlir. The current error message is as follows
> 
> The `is-usm-args=false` parameter for gpu pipeline was missing for some reason in `mlp.mlir` test. [Committed fix](https://github.com/intel/graph-compiler/pull/357/commits/f56eb398fcd08133788067649812619be1f79438) to this branch

Thanks a lot for help fixing this!

**Review by Yun-Fly — APPROVED** [review]

**Review by LongshengDu — APPROVED** [review]

**Pull request merged**
