### PR TITLE
Copy DecomposeAggregatedOps pass from tpp-mlir

### PR DESCRIPTION
**Pull request by xurui1995**
Copied from [tpp-mlir project ]( https://github.com/plaidml/tpp-mlir/blob/main/lib/TPP/Transforms/DecomposeAggregatedOps.cpp )
The current MLIR repo does not offer an easy-to-use pass for decomposing `linalg.softmax`, and `tpp-mlir` provide a solution
track: https://github.com/intel/graph-compiler/issues/214

### CODE REVIEW

**Comment by ZhennanQin** [comment]
We're waiting the upstream solution from: https://github.com/llvm/llvm-project/pull/97582. @kurapov-peter would you please provide some insights?

**Comment by xurui1995** [comment]
> We're waiting the upstream solution from: [llvm/llvm-project#97582](https://github.com/llvm/llvm-project/pull/97582). @kurapov-peter would you please provide some insights?

Oh, I did not notice this PR on llvm

**Comment by kurapov-peter** [comment]
Unfortunately it won't land in the nearest future. The decision is to create a generic decomposition mechanism (that I'm working on now). I could put a similar implementation into GC if we need it. Do we?

**Review by kurapov-peter — APPROVED** [review]

**Comment by ZhennanQin** [comment]
Please rebase.

**Review by ZhennanQin — APPROVED** [review]

**Pull request merged**
