### PR TITLE
update llvm revision

### PR DESCRIPTION
**Pull request by ZhennanQin**

### CODE REVIEW

**Comment by ZhennanQin** [comment]
Local build & test pass.

**Comment by WangJialei-A** [comment]
@ZhennanQin
image

@leshikus has upgraded the runner to version 0.0.2. 
Please help to upgrade the filter too.
https://github.com/intel/graph-compiler/blob/f3f116b84ea5ca48c1c1677f550a3a3b609de637/.github/workflows/build-llvm.yml#L11

**Comment by ZhennanQin** [comment]
@kurapov-peter Need your help here.

**Review by leshikus — APPROVED** [review]
LGTM

**Comment by leshikus** [comment]
The requested feature to support multiple llvm hashes is implemented. In rare cases it may require re-running some workflows of correspondent PR more than once (just re-running the same workflow should be enough).

**Review by AndreyPavlenko — APPROVED** [review]

**Pull request merged**
