### PR TITLE
Add numpy

### PR DESCRIPTION
**Pull request by leshikus**
Subj

### CODE REVIEW

**Review by WangJialei-A — APPROVED** [review]

**Review by ZhennanQin — APPROVED** [review]

**Comment by WangJialei-A** [comment]
Numpy is a dependency introduced from llvm. And we met dependency problem when build with python binding enabled llvm.
Please help to checkout the following file before build llvm & gc.
https://github.com/llvm/llvm-project/blob/main/mlir/python/requirements.txt

**Comment by WangJialei-A** [comment]
I raised PR #168 to handle numpy problem.
Let this PR focus on python3-dev problem

**Comment by WangJialei-A** [comment]
@leshikus 
Could you help to install `libomp5` in the image in this PR and redeploy the runner too?

**Comment by leshikus** [comment]
@WangJialei-A done, CI in your branch (slightly modified) is green with the new runner https://github.com/intel/graph-compiler/actions/runs/9942136805

**Review by WangJialei-A — APPROVED** [review]

**Pull request merged**
