### PR TITLE
action: Porting llvm format check

### PR DESCRIPTION
**Pull request by WangJialei-A**
Migrate clang format check from llvm-project
You can see the format check result here: #78

### CODE REVIEW

**Review by leshikus — COMMENTED** [review]
Do developers think the new variant is more convenient? I suggest them to review this.

I generally like shorter solutions. They cost less time to maintain.

**Comment by kurapov-peter** [comment]
The diff is nice to have I think, but clang format can do that with an option (I don't recall if it does so now, please correct me if I'm wrong @leshikus). @WangJialei-A, does this checker add anything clang-fromat cannot do?

**Comment by WangJialei-A** [comment]
> The diff is nice to have I think, but clang format can do that with an option (I don't recall if it does so now, please correct me if I'm wrong @leshikus). @WangJialei-A, does this checker add anything clang-fromat cannot do?

* Perform clang-format only on the changed files in the PR, not the whole repository. see [url](https://github.com/llvm/llvm-project/blob/0bced10f290bb96d675874a89f1b6789a2384e30/llvm/utils/git/code-format-helper.py#L352-L360)
* It can post the comment with robot account to tell developer how to fix or reproduce the problem, no need to sift through the error logs. See [url](https://github.com/intel/graph-compiler/pull/78#issuecomment-2113927353)

**Comment by kurapov-peter** [comment]
> > The diff is nice to have I think, but clang format can do that with an option (I don't recall if it does so now, please correct me if I'm wrong @leshikus). @WangJialei-A, does this checker add anything clang-fromat cannot do?
> 
> * Perform clang-format only on the changed files in the PR, not the whole repository. see [url](https://github.com/llvm/llvm-project/blob/0bced10f290bb96d675874a89f1b6789a2384e30/llvm/utils/git/code-format-helper.py#L352-L360)
> * It can post the comment with robot account to tell developer how to fix or reproduce the problem, no need to sift through the error logs. See [url](https://github.com/intel/graph-compiler/pull/78#issuecomment-2113927353)

I suggest removing the first point (running clang-format only on the changed files) as it doesn't save us any time on CI and adds unnecessary complexity.

For the second point, I suggest doing the same with pure clang-format if possible.

**Comment by WangJialei-A** [comment]
> > > The diff is nice to have I think, but clang format can do that with an option (I don't recall if it does so now, please correct me if I'm wrong @leshikus). @WangJialei-A, does this checker add anything clang-fromat cannot do?
> > 
> > 
> > 
> > * Perform clang-format only on the changed files in the PR, not the whole repository. see [url](https://github.com/llvm/llvm-project/blob/0bced10f290bb96d675874a89f1b6789a2384e30/llvm/utils/git/code-format-helper.py#L352-L360)
> > * It can post the comment with robot account to tell developer how to fix or reproduce the problem, no need to sift through the error logs. See [url](https://github.com/intel/graph-compiler/pull/78#issuecomment-2113927353)
> 
> I suggest removing the first point (running clang-format only on the changed files) as it doesn't save us any time on CI and adds unnecessary complexity.
> 
> For the second point, I suggest doing the same with pure clang-format if possible.

@kurapov-peter
If that's the case, then this PR is not necessary, and I will close this PR.

**Pull request closed without merging**
